### ISSUE TITLE
DST-MAT-SR-0080 : Meta Information association

### ISSUE THREAD

**Issue by antoineatrhea** [RHEAGROUP/DEH-MATLAB#13]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the DEHP-MATLAB
- [x] I have searched [open](https://github.com/RHEAGROUP/DEHP-MATLAB/issues) and [closed](https://github.com/RHEAGROUP/DEHP-MATLAB/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The Matlab DST adapter shall allow to associate parameters with meta information concerning reference coordinate systems. 

### System Configuration

- DEHPCommon version:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by lxatrhea** [comment]
@antoineatrhea Please ask OHB.
